name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug host variable
        run: |
          if [ -z "${{ secrets.EC2_HOST }}" ]; then
            echo "⚠️ EC2_HOST is missing!"
            exit 1
          else
            echo "✅ EC2_HOST is set (value hidden)."
          fi

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "Deploying new index.html to EC2"
            sudo cp index.html /var/www/html/index.html
            sudo systemctl restart httpd
